services:
  hardhat:
    image: node:18
    volumes:
      - ./:/srv
    working_dir: /srv
    ports:
        - "8545:8545"
    command: npx hardhat node --fork https://arb1.arbitrum.io/rpc --fork-block-number 225947589
