[store]
[store.primary]
connection = "postgresql://graph-node:let-me-in@postgres:5432/graph-node"
pool_size = 10

[chains]
ingestor = "default"

[chains.hardhat]
shard = "primary"
provider = [
  { label = "hardhat", details = { type = "web3", features = ['archive'], transport = "rpc", url = "http://evm:8545" } },
]

[chains.sepolia]
shard = "primary"
provider = [
  { label = "google", details = { type = "web3", features = ['archive'], transport = "rpc", url = "https://blockchain.googleapis.com/v1/projects/pexfi-com/locations/us-central1/endpoints/ethereum-sepolia/rpc?key=${GOOGLE_RPC_KEY}" } },
  { label = "alchemy", details = { type = "web3", features = ['archive'], transport = "ws", url = "wss://eth-sepolia.g.alchemy.com/v2/JPv_vpU3puJFVcnr7ptvxnCLo3hFhxYY" } }
]

[deployment]
[[deployment.rule]]
indexers = ["default"]
