[store]
[store.primary]
connection = "postgresql://graph-node:let-me-in@postgres:5432/graph-node"
pool_size = 10

[chains]
ingestor = "block_ingestor_node"

[chains.sepolia]
shard = "primary"
provider = [
  { label = "alchemy", details = { type = "web3", features = ['archive'], transport = "ws", url = "wss://eth-sepolia.g.alchemy.com/v2/JPv_vpU3puJFVcnr7ptvxnCLo3hFhxYY" } }
]

[deployment]
[[deployment.rule]]
indexers = ["default"]
